Downgrade matplotlib
Downgrade matplotlib to 2.1.2 because _cntr is missing in 2.1.2 later versions and tvb-framework need it in order to run with raise ImportError: cannot import name _cntr if not included.